# Generated by Django 3.2.7 on 2021-09-25 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Action Permission',
                'verbose_name_plural': 'Action Permissions',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='UserActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplyscript.actionpermission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Action Permission',
                'verbose_name_plural': 'User Action Permissions',
            },
        ),
        migrations.CreateModel(
            name='GroupActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplyscript.actionpermission')),
            ],
            options={
                'verbose_name': 'Group Action Permission',
                'verbose_name_plural': 'Group Action Permissions',
            },
        ),
        migrations.AddField(
            model_name='actionpermission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplyscript.module'),
        ),
        migrations.AddConstraint(
            model_name='actionpermission',
            constraint=models.UniqueConstraint(fields=('module', 'method'), name='actionpermission_module_method'),
        ),
    ]
