# Generated by Django 3.2.7 on 2021-10-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplyscript', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actionpermission',
            name='actionpermission_module_method',
        ),
        migrations.RemoveField(
            model_name='actionpermission',
            name='method',
        ),
        migrations.RemoveField(
            model_name='actionpermission',
            name='module',
        ),
        migrations.AddField(
            model_name='actionpermission',
            name='name',
            field=models.CharField(default=None, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
