# Generated by Django 3.2.7 on 2021-10-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplyscript', '0003_auto_20211011_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpermission',
            name='active_ind',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
